version: '3'
services:
  app:
    image: openjdk:11-jdk
    volumes:
      - appdata:/usr/data
    command:
      - apt update && apt install git default-jdk maven -y
      - git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      - mvn package -f /boxfuse-sample-java-war-hello/pom.xml
      - cp /boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/data
      - /bin/bash
  web:
    image: davidcaste/alpine-tomcat:jre7tomcat8
    volumes:
      - appdata:/usr/data
    ports:
      - 8080:8080
    depends_on:
      - app
    command:
      - cp /usr/data/hello-1.0.war /opt/tomcat/webapps/
      - /opt/tomcat/bin/catalina.sh run
volumes:
  appdata: