version: '3'
services:
  app:
    build: app/
    volumes:
      - appdata:/usr/data
    command:
      - /bin/bash
  web:
    build: web/
    volumes:
      - appdata:/usr/data
    ports:
      - 8080:8080
    depends_on:
      - app
    command:
      - cp /usr/data/hello-1.0.war /opt/tomcat/webapps/
      - /opt/tomcat/bin/catalina.sh run
volumes:
  appdata: