version: '3'
services:
  app:
    build: app/
    volumes:
      - appdata:/boxfuse-sample-java-war-hello/target
    command:
      - /bin/bash
  web:
    build: web/
    volumes:
      - appdata:/opt/tomcat/webapps/
    ports:
      - 8080:8080
    depends_on:
      - app
volumes:
  appdata: